---
- name: Set hostname on target machines
  hosts: monitor
  become: yes 
  tasks:

    - name: Set the hostname to inventory_hostname
      shell: hostnamectl set-hostname "{{ inventory_hostname }}"

